variables:
    SolutionBaseName: 'DFC.Composite.Shell'
    BuildPlatform: 'any cpu'
    BuildConfiguration: 'release'

jobs:

- job: BuildDotNetCore
  displayName: Build-DotNetCore
  pool:
    vmImage: 'VS2017-Win2016'
    demands:
      - DotNetFramework
      - msbuild
      - visualstudio
      - vstest
      - java

  steps:

  - task: SonarCloudPrepare@1
    inputs:
     SonarCloud: '$(SonarCloud)'
     organization: 'muthuramana-github'
     scannerMode: MSBuild
     projectKey: '$(SonarCloudKey)'
     projectName: 'mk-dfc-composite-shell'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet build application'
    inputs:
     command: build
     projects: '**/*.sln'
     arguments: '-o "$(build.artifactstagingdirectory)\Build\"'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet test application'
    inputs:
     command: test
     projects: '**/*Test.csproj'

  - task: SonarCloudAnalyze@1
  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'